
'------------------------------------------------------------------------------
' <auto-generated>
'    Dieser Code wurde aus einer Vorlage generiert.
'
'    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
'    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Objects
Imports System.Data.Objects.DataClasses
Imports System.Data.EntityClient
Imports System.ComponentModel
Imports System.Xml.Serialization
Imports System.Runtime.Serialization

<Assembly: EdmSchemaAttribute("291c62b0-154e-4a4d-8c90-692cc0879750")>

#Region "Kontexte"

''' <summary>
''' Keine Dokumentation für Metadaten verfügbar.
''' </summary>
Public Partial Class Model1Container
    Inherits ObjectContext

    #Region "Constructors"

    ''' <summary>
    ''' Initialisiert ein neues Model1Container-Objekt mithilfe der in Abschnitt 'Model1Container' der Anwendungskonfigurationsdatei gefundenen Verbindungszeichenfolge.
    ''' </summary>
    Public Sub New()
        MyBase.New("name=Model1Container", "Model1Container")
    MyBase.ContextOptions.LazyLoadingEnabled = true
        OnContextCreated()
    End Sub

    ''' <summary>
    ''' Initialisiert ein neues Model1Container-Objekt.
    ''' </summary>
    Public Sub New(ByVal connectionString As String)
        MyBase.New(connectionString, "Model1Container")
    MyBase.ContextOptions.LazyLoadingEnabled = true
        OnContextCreated()
    End Sub

    ''' <summary>
    ''' Initialisiert ein neues Model1Container-Objekt.
    ''' </summary>
    Public Sub New(ByVal connection As EntityConnection)
        MyBase.New(connection, "Model1Container")
    MyBase.ContextOptions.LazyLoadingEnabled = true
        OnContextCreated()
    End Sub

    #End Region

    #Region "Partial Methods"

    Partial Private Sub OnContextCreated()
    End Sub

    #End Region

End Class

#End Region

