'------------------------------------------------------------------------------
' <auto-generated>
'     Dieser Code wurde von einem Tool generiert.
'     Laufzeitversion:4.0.30319.42000
'
'     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
'     der Code erneut generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    '-Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    'Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    'mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    '''<summary>
    '''  Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("FOnline_2_Char_Planner.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        '''  Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _Stop() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_Stop", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ABoyDesc() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ABoyDesc", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        '''</summary>
        Friend ReadOnly Property Accession1() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Accession1", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property AchievAlAberDesc() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("AchievAlAberDesc", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property AchievAwarenessDesc() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("AchievAwarenessDesc", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property AchievHeaveDesc() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("AchievHeaveDesc", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property AchievMoGDesc() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("AchievMoGDesc", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property AchievPackRDesc() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("AchievPackRDesc", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property AchievPyroDesc() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("AchievPyroDesc", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property AchievWiHDesc() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("AchievWiHDesc", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property AClassDesc() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("AClassDesc", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        '''</summary>
        Friend ReadOnly Property aftertouch() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("aftertouch", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property AGDesc() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("AGDesc", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        '''</summary>
        Friend ReadOnly Property age_of_loneliness() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("age_of_loneliness", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        '''</summary>
        Friend ReadOnly Property anthrox() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("anthrox", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        '''</summary>
        Friend ReadOnly Property Anthrox9() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Anthrox9", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property AnticriticalDesc() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("AnticriticalDesc", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property AnticriticalDescNeu() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("AnticriticalDescNeu", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Antitoxin() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Antitoxin", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property AntitoxinDescPic() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("AntitoxinDescPic", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ARushDesc() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ARushDesc", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        '''</summary>
        Friend ReadOnly Property ATOMIC() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("ATOMIC", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property BarterDesc() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BarterDesc", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property BarterDescPicNew() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BarterDescPicNew", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property BetterCrDesc() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BetterCrDesc", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property BGunsDesc() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BGunsDesc", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property BHeadDesc() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BHeadDesc", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property BHtHAtDesc() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BHtHAtDesc", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property BHtHDmgDesc() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BHtHDmgDesc", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property BlMessDesc() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BlMessDesc", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property BooksDesc() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BooksDesc", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property BRDDesc() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BRDDesc", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        '''</summary>
        Friend ReadOnly Property BREAKLINE() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("BREAKLINE", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property BRoFDesc() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BRoFDesc", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property BruiserDesc() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BruiserDesc", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property BruiserDescTest() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BruiserDescTest", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Buffout() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Buffout", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property BuffoutDescPic() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BuffoutDescPic", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property BuffoutHigh() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BuffoutHigh", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property BuffoutHighNew() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BuffoutHighNew", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property BuffoutNew() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BuffoutNew", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.IO.UnmanagedMemoryStream ähnlich wie System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property button_27() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("button_27", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.IO.UnmanagedMemoryStream ähnlich wie System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property button_29() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("button_29", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.IO.UnmanagedMemoryStream ähnlich wie System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property button_30() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("button_30", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.IO.UnmanagedMemoryStream ähnlich wie System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property button_46() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("button_46", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.IO.UnmanagedMemoryStream ähnlich wie System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property button_50() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("button_50", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        '''</summary>
        Friend ReadOnly Property Cascade4() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Cascade4", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        '''</summary>
        Friend ReadOnly Property castlevania_1() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("castlevania_1", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        '''</summary>
        Friend ReadOnly Property Cave8() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Cave8", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property CCombatDesc() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CCombatDesc", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property CCombDescPicNew() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CCombDescPicNew", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property CHDesc() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CHDesc", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ChemControlImpDesc() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ChemControlImpDesc", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        '''</summary>
        Friend ReadOnly Property chris_glaister___lost_patrol_theme() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("chris_glaister___lost_patrol_theme", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Cigarettes() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Cigarettes", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property CigarettesHigh() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CigarettesHigh", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property CigarettesHighNew() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CigarettesHighNew", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property CigarettesNew() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CigarettesNew", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property CigsDescPic() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CigsDescPic", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        '''</summary>
        Friend ReadOnly Property Classic3() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Classic3", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.IO.UnmanagedMemoryStream ähnlich wie System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property click() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("click", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        '''</summary>
        Friend ReadOnly Property Crash2() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Crash2", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Creditsneu() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Creditsneu", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Creditsneu_v1_4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Creditsneu_v1_4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Creditsneu_v1_5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Creditsneu_v1_5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property CReliantDesc() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CReliantDesc", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property CResistDesc() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CResistDesc", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property CritChanceDesc() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CritChanceDesc", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        '''</summary>
        Friend ReadOnly Property ctsewer() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("ctsewer", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property CWeightDesc() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CWeightDesc", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        '''</summary>
        Friend ReadOnly Property Defjam3() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Defjam3", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        '''</summary>
        Friend ReadOnly Property Delight7() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Delight7", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        '''</summary>
        Friend ReadOnly Property denaris_remix() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("denaris_remix", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        '''</summary>
        Friend ReadOnly Property DESIRATA() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("DESIRATA", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property DocDesc() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DocDesc", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property DocDescPicNew() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DocDescPicNew", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property DodgerDesc() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DodgerDesc", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        '''</summary>
        Friend ReadOnly Property DREAMWEB_04() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("DREAMWEB_04", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        '''</summary>
        Friend ReadOnly Property dreamweb_ingame() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("dreamweb_ingame", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        '''</summary>
        Friend ReadOnly Property DREAMWEB2() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("DREAMWEB2", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        '''</summary>
        Friend ReadOnly Property dreamweb4() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("dreamweb4", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        '''</summary>
        Friend ReadOnly Property DREAMWEB6() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("DREAMWEB6", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property DResistDesc() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DResistDesc", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        '''</summary>
        Friend ReadOnly Property Dubmood___3D_galaxy() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Dubmood___3D_galaxy", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property EarlSeqDesc() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("EarlSeqDesc", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property EducatedDesc() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("EducatedDesc", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ENDesc() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ENDesc", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property EnvImplDesc() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("EnvImplDesc", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        '''</summary>
        Friend ReadOnly Property ERTERTER() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("ERTERTER", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        '''</summary>
        Friend ReadOnly Property Estrayk___The_HER_song_10() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Estrayk___The_HER_song_10", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property EvaderDesc() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("EvaderDesc", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property EWDesc() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("EWDesc", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        '''</summary>
        Friend ReadOnly Property FACTORY() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("FACTORY", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property FADesc() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FADesc", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property FAidDescPicNew() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FAidDescPicNew", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Icon ähnlich wie (Symbol).
        '''</summary>
        Friend ReadOnly Property favicon() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("favicon", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Icon ähnlich wie (Symbol).
        '''</summary>
        Friend ReadOnly Property favicon_1_() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("favicon_1_", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        '''</summary>
        Friend ReadOnly Property feather() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("feather", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property FinesseDesc() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FinesseDesc", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property FMetaDesc() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FMetaDesc", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property FMetaDescPic() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FMetaDescPic", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Icon ähnlich wie (Symbol).
        '''</summary>
        Friend ReadOnly Property FOPlanner() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("FOPlanner", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property FShotDesc() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FShotDesc", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        '''</summary>
        Friend ReadOnly Property FUCKFUCK() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("FUCKFUCK", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property GAGDesc() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("GAGDesc", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property GainCHDesc() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("GainCHDesc", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property GainINDesc() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("GainINDesc", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property GainPEDesc() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("GainPEDesc", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property GainSTDesc() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("GainSTDesc", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property GamblingDesc() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("GamblingDesc", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property GENDesc() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("GENDesc", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property GhostDesc() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("GhostDesc", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property GlowQuestDesc() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("GlowQuestDesc", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property GLuckDesc() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("GLuckDesc", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property GNaturedDesc() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("GNaturedDesc", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property HarmlessDesc() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("HarmlessDesc", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property HealRateDesc() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("HealRateDesc", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        '''</summary>
        Friend ReadOnly Property her1() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("her1", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        '''</summary>
        Friend ReadOnly Property her10() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("her10", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        '''</summary>
        Friend ReadOnly Property her2() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("her2", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        '''</summary>
        Friend ReadOnly Property her3() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("her3", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        '''</summary>
        Friend ReadOnly Property Her4() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Her4", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        '''</summary>
        Friend ReadOnly Property her5() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("her5", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        '''</summary>
        Friend ReadOnly Property her6() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("her6", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        '''</summary>
        Friend ReadOnly Property her7() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("her7", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        '''</summary>
        Friend ReadOnly Property her8() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("her8", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        '''</summary>
        Friend ReadOnly Property her9() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("her9", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property HHandedDesc() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("HHandedDesc", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Hintergrund() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Hintergrund", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ImplAccurDesc() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ImplAccurDesc", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ImplDefDesc() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ImplDefDesc", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ImplEngDesc() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ImplEngDesc", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ImplEnhanceDesc() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ImplEnhanceDesc", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ImplSpeedDesc() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ImplSpeedDesc", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ImplSurvivalDesc() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ImplSurvivalDesc", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property INDesc() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("INDesc", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        '''</summary>
        Friend ReadOnly Property Jakim___Whatever_it_means() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Jakim___Whatever_it_means", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Jet() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Jet", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property JetDescPic() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("JetDescPic", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property JetHigh() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("JetHigh", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property JinxedDesc() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("JinxedDesc", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        '''</summary>
        Friend ReadOnly Property Joule_and_Coda___Going_nuts() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Joule_and_Coda___Going_nuts", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        '''</summary>
        Friend ReadOnly Property Joy_and_Magnificent_Force2() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Joy_and_Magnificent_Force2", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property JTQuestMaryDesc() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("JTQuestMaryDesc", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property JTQuestPeteDesc() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("JTQuestPeteDesc", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property KamikazeDesc() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("KamikazeDesc", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        '''</summary>
        Friend ReadOnly Property Key_G___Red_green_blue_5() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Key_G___Red_green_blue_5", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        '''</summary>
        Friend ReadOnly Property lastnin1() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("lastnin1", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property LifeGDesc() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LifeGDesc", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property LivingADesc() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LivingADesc", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property LKDesc() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LKDesc", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        '''</summary>
        Friend ReadOnly Property LOST() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("LOST", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property LPDesc() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LPDesc", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property LPickDescPicNew() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LPickDescPicNew", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property LStepDesc() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LStepDesc", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        '''</summary>
        Friend ReadOnly Property m1993() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("m1993", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        '''</summary>
        Friend ReadOnly Property m2000AD() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("m2000AD", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MagneticPDesc() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MagneticPDesc", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MarksmanImplDesc() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MarksmanImplDesc", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MaxAPDesc() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MaxAPDesc", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MaxHPDesc() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MaxHPDesc", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MCritsDesc() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MCritsDesc", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MedicalImplDesc() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MedicalImplDesc", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MedicDesc() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MedicDesc", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MeleeDmgDesc() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MeleeDmgDesc", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        '''</summary>
        Friend ReadOnly Property Millenium1() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Millenium1", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MrFixitDesc() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MrFixitDesc", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        '''</summary>
        Friend ReadOnly Property MUSIC() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("MUSIC", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MutantDesc() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MutantDesc", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property NeutralDesc() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("NeutralDesc", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Nuka() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Nuka", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property NukaDescPic() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("NukaDescPic", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property NukaHigh() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("NukaHigh", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ODDEsc() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ODDEsc", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ODManDescPicNew() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ODManDescPicNew", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property OneHanderDesc() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("OneHanderDesc", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        '''</summary>
        Friend ReadOnly Property PACKCHP1() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("PACKCHP1", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property pause() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pause", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property PEDesc() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PEDesc", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property PFinderDesc() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PFinderDesc", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Play() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Play", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Pointer() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Pointer", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property PoisonResDesc() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PoisonResDesc", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        '''</summary>
        Friend ReadOnly Property Prestige3() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Prestige3", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        '''</summary>
        Friend ReadOnly Property Prestige4() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Prestige4", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Psycho() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Psycho", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property PsychoDescPic() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PsychoDescPic", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property PsychoHigh() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PsychoHigh", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property QHandsDesc() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("QHandsDesc", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property QRecDesc() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("QRecDesc", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property RadResDesc() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("RadResDesc", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        '''</summary>
        Friend ReadOnly Property rastaman() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("rastaman", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property RepairDesc() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("RepairDesc", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property RepairDescPicNew() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("RepairDescPicNew", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ScavengeDesc() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ScavengeDesc", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ScavengeDescPicNew() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ScavengeDescPicNew", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ScienceDesc() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ScienceDesc", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ScienceDescPicNew() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ScienceDescPicNew", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ScoutImplDesc() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ScoutImplDesc", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        '''</summary>
        Friend ReadOnly Property SECRET() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("SECRET", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property SequenceDesc() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SequenceDesc", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property SFrameDesc() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SFrameDesc", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property SGunsDesc() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SGunsDesc", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property SightDescr() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SightDescr", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property SilentRDesc() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SilentRDesc", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Skip() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Skip", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        '''</summary>
        Friend ReadOnly Property Slash___Because() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Slash___Because", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property SneakDesc() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SneakDesc", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property SneakDescPicNew() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SneakDescPicNew", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        '''</summary>
        Friend ReadOnly Property SNORWALK() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("SNORWALK", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property SpeechDesc() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SpeechDesc", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property SShootDesc() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SShootDesc", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Standby() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Standby", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property StandbySW() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("StandbySW", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property STDesc() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("STDesc", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property StealDesc() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("StealDesc", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property StealDescPicNew() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("StealDescPicNew", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property StrBackDesc() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("StrBackDesc", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property StWallDesc() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("StWallDesc", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        '''</summary>
        Friend ReadOnly Property Supplex1() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Supplex1", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        '''</summary>
        Friend ReadOnly Property Tempest___Acidjazzed_evening() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Tempest___Acidjazzed_evening", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ThiefDesc() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ThiefDesc", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ThoughDesc() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ThoughDesc", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ThrowDesc() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ThrowDesc", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TrapsDesc() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TrapsDesc", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        '''</summary>
        Friend ReadOnly Property TRSI_and_Zenith2() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("TRSI_and_Zenith2", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        '''</summary>
        Friend ReadOnly Property turrican2ingame1rmx() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("turrican2ingame1rmx", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        '''</summary>
        Friend ReadOnly Property turrican2titlermx() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("turrican2titlermx", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Volume0() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Volume0", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Volume25() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Volume25", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Volume50() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Volume50", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Volume75() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Volume75", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property VolumeFull() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("VolumeFull", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property VolumeMute() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("VolumeMute", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        '''</summary>
        Friend ReadOnly Property Wave___1999() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Wave___1999", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        '''</summary>
        Friend ReadOnly Property WCD1() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("WCD1", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        '''</summary>
        Friend ReadOnly Property WDC3() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("WDC3", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        '''</summary>
        Friend ReadOnly Property WDC4() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("WDC4", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property WHandlDesc() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("WHandlDesc", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        '''</summary>
        Friend ReadOnly Property Wiklund___Bonfire() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Wiklund___Bonfire", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
    End Module
End Namespace
